[package]
name = "peudo_write_ret"
version = "0.1.0"
authors = ["Grzegorz Wierzowiecki <gww@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
